// This file is auto-generated by nextjs-studio.
// Do not edit manually — re-run `npx nextjs-studio --generate-types` to update.

// Branded scalar types — structurally strings/numbers but semantically distinct.
declare const __brand: unique symbol;
type Brand<T, B extends string> = T & { readonly [__brand]: B };

export type Email     = Brand<string, 'Email'>;
export type HttpUrl   = Brand<string, 'HttpUrl'>;
export type ISODate   = Brand<string, 'ISODate'>;
export type MediaPath = Brand<string, 'MediaPath'>;
export type ID        = Brand<string, 'ID'>;
export type Slug      = Brand<string, 'Slug'>;

/** Data shape for the "about" collection. */
export interface AboutEntry {
  name: string;
  greeting: string;
  roles: Array<"Mobile Developer" | "Bug Hunter">;
  avatar: HttpUrl;
  bio: string;
  bioExtra: string;
  seoDescription: string;
  cvUrl: HttpUrl;
  email: Email;
}

/** Data shape for the "atom" collection. */
export interface AtomEntry {
  name: string;
  description: string;
}

/** Data shape for the "aur" collection. */
export interface AurEntry {
  name: string;
  url: HttpUrl;
  description: string;
}

/** Data shape for the "contacts" collection. */
export interface ContactsEntry {
  url: string;
  icon: string;
  label: string;
}

/** Data shape for the "expertise" collection. */
export interface ExpertiseEntry {
  title: string;
  description: string;
  icon: string;
  link: string;
}

/** Data shape for the "github" collection. */
export interface GithubEntry {
  id: number;
  node_id: string;
  name: string;
  full_name: string;
  private: boolean;
  owner: {
    login: string;
    id: number;
    node_id: string;
    avatar_url: HttpUrl;
    gravatar_id: string;
    url: HttpUrl;
    html_url: HttpUrl;
    followers_url: HttpUrl;
    following_url: HttpUrl;
    gists_url: HttpUrl;
    starred_url: HttpUrl;
    subscriptions_url: HttpUrl;
    organizations_url: HttpUrl;
    repos_url: HttpUrl;
    events_url: HttpUrl;
    received_events_url: HttpUrl;
    type: string;
    user_view_type: string;
    site_admin: boolean;
  };
  html_url: HttpUrl;
  description: string;
  fork: boolean;
  url: HttpUrl;
  forks_url: HttpUrl;
  keys_url: HttpUrl;
  collaborators_url: HttpUrl;
  teams_url: HttpUrl;
  hooks_url: HttpUrl;
  issue_events_url: HttpUrl;
  events_url: HttpUrl;
  assignees_url: HttpUrl;
  branches_url: HttpUrl;
  tags_url: HttpUrl;
  blobs_url: HttpUrl;
  git_tags_url: HttpUrl;
  git_refs_url: HttpUrl;
  trees_url: HttpUrl;
  statuses_url: HttpUrl;
  languages_url: HttpUrl;
  stargazers_url: HttpUrl;
  contributors_url: HttpUrl;
  subscribers_url: HttpUrl;
  subscription_url: HttpUrl;
  commits_url: HttpUrl;
  git_commits_url: HttpUrl;
  comments_url: HttpUrl;
  issue_comment_url: HttpUrl;
  contents_url: HttpUrl;
  compare_url: HttpUrl;
  merges_url: HttpUrl;
  archive_url: HttpUrl;
  downloads_url: HttpUrl;
  issues_url: HttpUrl;
  pulls_url: HttpUrl;
  milestones_url: HttpUrl;
  notifications_url: HttpUrl;
  labels_url: HttpUrl;
  releases_url: HttpUrl;
  deployments_url: HttpUrl;
  created_at: Date;
  updated_at: Date;
  pushed_at: Date;
  git_url: string;
  ssh_url: Email;
  clone_url: HttpUrl;
  svn_url: HttpUrl;
  homepage: string;
  size: number;
  stargazers_count: number;
  watchers_count: number;
  language: string;
  has_issues: boolean;
  has_projects: boolean;
  has_downloads: boolean;
  has_wiki: boolean;
  has_pages: boolean;
  has_discussions: boolean;
  forks_count: number;
  mirror_url: string;
  archived: boolean;
  disabled: boolean;
  open_issues_count: number;
  license: {
    key: string;
    name: string;
    spdx_id: string;
    url: HttpUrl;
    node_id: string;
  };
  allow_forking: boolean;
  is_template: boolean;
  web_commit_signoff_required: boolean;
  has_pull_requests: boolean;
  pull_request_creation_policy: string;
  topics: Array<"github-app" | "github-bot" | "license" | "probot" | "probot-app" | "anonymous" | "database" | "example" | "ifpa" | "mysql" | "report" | "reporting" | "reporting-tool" | "system" | "example-app" | "lecture-material" | "node" | "nuxt" | "vue" | "xss" | "xss-example" | "xss-vulnerability" | "atom" | "atom-package" | "atom-plugin" | "terminal" | "awesome" | "awesome-list" | "handlebars" | "lists" | "polybar" | "proton" | "steam" | "steamplay" | "bds" | "flat" | "tampermonkey" | "theme" | "hacktoberfest" | "cerebro" | "cerebro-plugin" | "xkcd" | "xkcd-client" | "json" | "licenses" | "licensing" | "list" | "open-source" | "package" | "bin">;
  visibility: string;
  forks: number;
  open_issues: number;
  watchers: number;
  default_branch: string;
}

/** Data shape for the "googleplay" collection. */
export interface GoogleplayEntry {
  name: string;
  slug: string;
  tagline: string;
  url: HttpUrl;
  description: string;
  storeDescription: string;
  category: string;
  icon: string;
  accentColor: string;
  features: Array<{
    icon: string;
    title: string;
    description: string;
  }>;
  buildStory: {
    problem: string;
    solution: string;
    learned: string;
  };
  tags: Array<"flutter" | "photography" | "creative" | "instagram" | "freemium" | "relaxation" | "sleep" | "white noise" | "ambient" | "game" | "survival" | "arcade" | "bonfire" | "education" | "CNH" | "DETRAN" | "gamification" | "brazil" | "android" | "ios" | "memory" | "jetpack compose" | "open source" | "pets" | "marketplace" | "services">;
}

/** Data shape for the "links" collection. */
export interface LinksEntry {
  title: string;
  url: HttpUrl;
  icon: string;
  enabled: boolean;
}

/** Data shape for the "luarocks" collection. */
export interface LuarocksEntry {
  name: string;
  description: string;
}

/** Data shape for the "menu" collection. */
export interface MenuEntry {
  title: string;
  href: string;
}

/** Data shape for the "npm" collection. */
export interface NpmEntry {
  name: string;
  scope: string;
  version: string;
  description: string;
  keywords: Array<"orgmanager" | "api" | "github-app" | "github-bot" | "license" | "probot" | "probot-app" | "example" | "example-app" | "lecture-material" | "node" | "nuxt" | "vue" | "xss" | "xss-example" | "xss-vulnerability" | "proton" | "awesome" | "awesome-list" | "steam" | "games" | "list" | "cerebro" | "cerebro-plugin" | "xkcd" | "licenses" | "mit" | "open source" | "choosealicense" | "spdx" | "cp" | "random" | "files" | "folder" | "bin" | "cli" | "ghpages" | "generation" | "github" | "bot" | "html" | "git" | "unsplash" | "wallpaper" | "telegram" | "grupo" | "desenvolvimento" | "bots" | "debug" | "console">;
  date: Date;
  links: {
    npm: HttpUrl;
    homepage: HttpUrl;
    repository: HttpUrl;
    bugs: HttpUrl;
  };
  author: {
    name: string;
    email: Email;
    url: HttpUrl;
    username: string;
  };
  publisher: {
    username: string;
    email: Email;
  };
  maintainers: Array<{
    username: string;
    email: Email;
  }>;
  downloads: number;
}

/** Data shape for the "offline" collection. */
export interface OfflineEntry {
  name: string;
  description: string;
}

/** Data shape for the "posts" collection. */
export interface PostsEntry {
  title: string;
  date: string;
  description: string;
  slug: string;
  originalUrl: HttpUrl;
  lang: string;
  cover: string;
  tags: Array<"Android" | "Mobile" | "UI/UX" | "Video" | "Flutter" | "iOS" | "AI" | "Article" | "JavaScript" | "React" | "GitHub" | "DevOps" | "Tutorial" | "Testing" | "Web" | "Frontend" | "Tools" | "Career" | "Linux" | "Performance" | "Security">;
}

/** Data shape for the "private" collection. */
export interface PrivateEntry {
  name: string;
  url: HttpUrl;
  description: string;
}

/** Data shape for the "projects" collection. */
export interface ProjectsEntry {
  title: string;
  description: string;
  imageUrl: string;
  href: HttpUrl;
}

/** Data shape for the "pypi" collection. */
export interface PypiEntry {
  name: string;
  description: string;
}

/** Data shape for the "skills" collection. */
export interface SkillsEntry {
  category: string;
  items: Array<{
    name: string;
    icon: string;
    color: string;
  }>;
}

/** Data shape for the "sociallinks" collection. */
export interface SociallinksEntry {
  label: string;
  url: HttpUrl;
  icon: string;
}

/** Data shape for the "talks" collection. */
export interface TalksEntry {
  id: number;
  date: string;
  title: string;
  description: string;
  event: string;
  tags: Array<"devops" | "mobile" | "firebase" | "flutter" | "code" | "documentation" | "react-native" | "performance" | "testing" | "fastlane" | "ios" | "web" | "IA" | "javascript" | "GIT" | "wordpress" | "linkedin" | "career" | "feature-flags" | "mcp" | "ia">;
  youtubeUrl: HttpUrl;
}

/** Data shape for the "testimonials" collection. */
export interface TestimonialsEntry {
  name: string;
  role: string;
  company: string;
  quote: string;
  avatar: string;
}

/** Data shape for the "timeline" collection. */
export interface TimelineEntry {
  date: string;
  title: string;
  description: string;
  tags: Array<"ctf" | "cybersecurity" | "xibesec" | "competition" | "events" | "ai" | "android" | "claudecode" | "automation" | "mcp" | "projeto" | "career" | "mobile" | "owasp" | "talks" | "devops" | "featureflags" | "devopsdays" | "security" | "saas" | "backend" | "infosec" | "content" | "cursor" | "gitlab" | "flutter" | "produto" | "ia" | "editor" | "googledevfest" | "firebase" | "testesab" | "gdg" | "googleio" | "cleancode" | "devsnorte" | "estudo" | "marketingdigital" | "desenvolvimentopessoal" | "reactnative" | "sdk" | "opensource" | "hacktoberfest" | "gamedev" | "bonfireengine" | "hackathon" | "braziljs" | "ifpa" | "arduino" | "highschool">;
}

/** Data shape for the "volunteer" collection. */
export interface VolunteerEntry {
  organization: string;
  role: string;
  startDate: string;
  endDate: string;
  logo: string;
  description: string;
  category: string;
}

/** Data shape for the "windows" collection. */
export interface WindowsEntry {
  name: string;
  url: HttpUrl;
  description: string;
}

/** Data shape for the "work" collection. */
export interface WorkEntry {
  company: string;
  role: string;
  startDate: string;
  endDate: string;
  logo: string;
  description: string;
}

// Augment both entry points so queryCollection() is fully typed regardless of import path.
declare module 'nextjs-studio' {
  interface CollectionTypeMap {
    "about": AboutEntry;
    "atom": AtomEntry;
    "aur": AurEntry;
    "contacts": ContactsEntry;
    "expertise": ExpertiseEntry;
    "github": GithubEntry;
    "googleplay": GoogleplayEntry;
    "links": LinksEntry;
    "luarocks": LuarocksEntry;
    "menu": MenuEntry;
    "npm": NpmEntry;
    "offline": OfflineEntry;
    "posts": PostsEntry;
    "private": PrivateEntry;
    "projects": ProjectsEntry;
    "pypi": PypiEntry;
    "skills": SkillsEntry;
    "sociallinks": SociallinksEntry;
    "talks": TalksEntry;
    "testimonials": TestimonialsEntry;
    "timeline": TimelineEntry;
    "volunteer": VolunteerEntry;
    "windows": WindowsEntry;
    "work": WorkEntry;
  }
}
declare module 'nextjs-studio/server' {
  interface CollectionTypeMap {
    "about": AboutEntry;
    "atom": AtomEntry;
    "aur": AurEntry;
    "contacts": ContactsEntry;
    "expertise": ExpertiseEntry;
    "github": GithubEntry;
    "googleplay": GoogleplayEntry;
    "links": LinksEntry;
    "luarocks": LuarocksEntry;
    "menu": MenuEntry;
    "npm": NpmEntry;
    "offline": OfflineEntry;
    "posts": PostsEntry;
    "private": PrivateEntry;
    "projects": ProjectsEntry;
    "pypi": PypiEntry;
    "skills": SkillsEntry;
    "sociallinks": SociallinksEntry;
    "talks": TalksEntry;
    "testimonials": TestimonialsEntry;
    "timeline": TimelineEntry;
    "volunteer": VolunteerEntry;
    "windows": WindowsEntry;
    "work": WorkEntry;
  }
}
