import type { Meta, StoryObj } from '@storybook/nextjs';
import { expect, within } from 'storybook/test';

import { LanguageSelect } from './LanguageSelect';

const meta = {
  title: 'UI/LanguageSelect',
  component: LanguageSelect,
  parameters: { layout: 'centered' },
  args: { current: 'en', pathname: '/about' },
} satisfies Meta<typeof LanguageSelect>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * The footer switcher on a route that exists in both languages. Labels are
 * endonyms, so a reader hunting for their own language reads it in it.
 */
export const Default: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    // The active language is not a link: there is nowhere to go.
    await expect(canvas.getByText('English')).toHaveAttribute('aria-current', 'true');
    await expect(canvas.getByRole('link', { name: 'Português' })).toHaveAttribute(
      'href',
      '/br/about'
    );
  },
};

/** Rendered from a Portuguese page: the pair swaps roles. */
export const OnPortuguesePage: Story = {
  args: { current: 'br', pathname: '/br/about' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.getByRole('link', { name: 'English' })).toHaveAttribute('href', '/about');
  },
};

/**
 * The pathname as it reads *during the export*, which is the one that ends up
 * in the shipped HTML.
 *
 * English pages are built at `/en/**` and moved to the root afterwards, so
 * `usePathname()` reports `/en/about` while the page is being rendered. Left
 * unrecognised, that segment travelled into the href and every English page
 * shipped pointing at `/br/en/<path>/`, a tree that has never existed. The
 * reader only ever saw the right link if they waited for hydration; a crawler
 * saw the 404.
 */
export const OnABuildTimeEnglishPath: Story = {
  args: { current: 'en', pathname: '/en/timeline/2012/my-first-website' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.getByRole('link', { name: 'Português' })).toHaveAttribute(
      'href',
      '/br/timeline/2012/my-first-website'
    );
  },
};

/** The same, on the home, where the build-time path is the bare `/en`. */
export const OnTheBuildTimeEnglishHome: Story = {
  args: { current: 'en', pathname: '/en' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.getByRole('link', { name: 'Português' })).toHaveAttribute('href', '/br');
  },
};

/**
 * A route that used to have no Portuguese page. There are none left: every
 * route lives under `[lang]` and is rendered once per locale, so the switcher
 * always has somewhere to send the reader.
 */
export const OnProjects: Story = {
  args: { current: 'en', pathname: '/projects' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.getByRole('link', { name: 'Português' })).toHaveAttribute(
      'href',
      '/br/projects'
    );
  },
};

/**
 * A blog post. Posts always exist in both languages: the locale is a filename
 * suffix on the MDX source, so the counterpart is generated by construction.
 *
 * The Portuguese URL is the prefix form like every other route. The old
 * trailing `/pt` is still understood on the way in, but nothing writes it.
 */
export const OnAPost: Story = {
  args: { current: 'en', pathname: '/post/arrow-function-vs-normal-function' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.getByRole('link', { name: 'Português' })).toHaveAttribute(
      'href',
      '/br/post/arrow-function-vs-normal-function'
    );
  },
};

/** Every locale in the site's list, to check the row still reads at its widest. */
export const AllLocales: Story = {
  args: { current: 'br', pathname: '/br' },
};
