import type { Meta, StoryObj } from '@storybook/nextjs';
import { expect, within } from 'storybook/test';

import { LanguageSelect } from './LanguageSelect';

const meta = {
  title: 'UI/LanguageSelect',
  component: LanguageSelect,
  parameters: { layout: 'centered' },
  args: { current: 'en', pathname: '/about' },
} satisfies Meta<typeof LanguageSelect>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * The footer switcher on a route that exists in both languages. Labels are
 * endonyms, so a reader hunting for their own language reads it in it.
 */
export const Default: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    // The active language is not a link: there is nowhere to go.
    await expect(canvas.getByText('English')).toHaveAttribute('aria-current', 'true');
    await expect(canvas.getByRole('link', { name: 'Português' })).toHaveAttribute(
      'href',
      '/br/about'
    );
  },
};

/** Rendered from a Portuguese page: the pair swaps roles. */
export const OnPortuguesePage: Story = {
  args: { current: 'br', pathname: '/br/about' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.getByRole('link', { name: 'English' })).toHaveAttribute('href', '/about');
  },
};

/**
 * A route with no translation yet. Portuguese renders inert rather than hidden
 * or pointing somewhere else, with a screen-reader-only reason.
 */
export const UntranslatedRoute: Story = {
  args: { current: 'en', pathname: '/projects' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.queryByRole('link', { name: /Português/ })).not.toBeInTheDocument();
    await expect(canvas.getByText(/Português/)).toHaveAttribute('aria-disabled', 'true');
  },
};

/**
 * A blog post. Posts always exist in both languages: the locale is a filename
 * suffix on the MDX source, so the counterpart is generated by construction.
 */
export const OnAPost: Story = {
  args: { current: 'en', pathname: '/post/arrow-function-vs-normal-function' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(canvas.getByRole('link', { name: 'Português' })).toHaveAttribute(
      'href',
      '/post/arrow-function-vs-normal-function/pt'
    );
  },
};

/** Every locale in the site's list, to check the row still reads at its widest. */
export const AllLocales: Story = {
  args: { current: 'br', pathname: '/br' },
};
